### PR TITLE
Set Wallpaper on Windows and Linux (GNOME based) directly [REDEFINED]

### PR DESCRIPTION
**Pull request by priyamharsh14**
#49 Have a look.. I made the required changes to the code..

### CODE REVIEW

**Comment by SubhrajitPrusty** [comment]
Thanks. I'll verify on a windows machine tonight and continue afterwards.

**Comment by priyamharsh14** [comment]
Sure

**Comment by SubhrajitPrusty** [comment]
Did you even run the program after making changes?

**Comment by priyamharsh14** [comment]
> Did you even run the program after making changes?

No, I ran it last time where the code asked for input to set the wallpaper..
I will run it now and if there's any issue, I will fix it ASAP

**Comment by priyamharsh14** [comment]
Its done now..
Everything is working now..

**Comment by priyamharsh14** [comment]
I am working on set wallpaper in Linux System (GNOME based)

**Comment by priyamharsh14** [comment]
#49 Done !!

**Comment by SubhrajitPrusty** [comment]
Thanks for the work but #55 has a better implementation covering multiple OS and DEs.

**Pull request closed without merging**
